from __future__ import annotations
from datetime import datetime
from typing import Iterable, Protocol, Sequence
from ec.knowledge.model import KnowledgeRecord

class KnowledgeRepository(Protocol):
    def append(self, record: KnowledgeRecord) -> None: ...
    def get(self, record_id: str) -> KnowledgeRecord | None: ...
    def query(self, *, text: str | None = None, tenant_id: str | None = None,
              kinds: Sequence[str] | None = None, at: datetime | None = None,
              limit: int = 100) -> list[KnowledgeRecord]: ...

class EvidenceArchive(Protocol):
    def put(self, content: bytes, *, media_type: str, source_uri: str) -> str: ...
    def get(self, evidence_id: str) -> bytes: ...

class SearchProjection(Protocol):
    def upsert(self, record: KnowledgeRecord) -> None: ...
    def search(self, query: str, *, limit: int) -> list[str]: ...

class VectorProjection(Protocol):
    def upsert_vector(self, record_id: str, vector: Sequence[float], metadata: dict[str, str]) -> None: ...
    def nearest(self, vector: Sequence[float], *, limit: int) -> list[str]: ...

class GraphProjection(Protocol):
    def upsert_record(self, record: KnowledgeRecord) -> None: ...
    def neighborhood(self, subject: str, *, depth: int = 1, limit: int = 100) -> list[str]: ...
