import assert from "node:assert/strict";
import fs from "node:fs";
import { compileForm } from "../dist/index.js";
const input = JSON.parse(fs.readFileSync(new URL("../examples/evo-sales-order.snapshot.json", import.meta.url), "utf8"));
const expected = JSON.parse(fs.readFileSync(new URL("../examples/expected-sales-order.uidl.json", import.meta.url), "utf8"));
const a = compileForm(input);
const b = compileForm(JSON.parse(JSON.stringify(input)));
assert.deepEqual(a, expected, "compiled UIDL must match executable spec");
assert.deepEqual(a, b, "compilation must be deterministic");
assert.equal(a.command.code, "approve-sales-order");
assert.equal(a.fields.find(f => f.key === "quantity").control, "number");
console.log("EC-M0 PASS");
